-- Add the static free tools to the database so they appear in admin panel
INSERT INTO products (
  id,
  name,
  slug,
  description,
  image_url,
  category_id,
  product_type,
  is_free,
  is_featured,
  is_newly_launched,
  is_popular,
  is_trending,
  is_editors_choice,
  affiliate_link,
  cta_button_text,
  views_count,
  saves_count,
  is_embedded_tool,
  tool_type,
  tool_url
) VALUES 
(
  'ae7b8c9d-1234-5678-9abc-def012345678',
  'Percentage Calculator',
  'percentage-calculator',
  'Calculate percentages, percentage changes, and percentage of totals with ease.',
  '/src/assets/percentage-calculator-icon.jpg',
  'a3f55a64-e095-4cb8-a4d4-1dbc703051d2', -- Productivity Apps category
  'free_tools',
  true,
  false,
  true,
  false,
  false,
  false,
  '/tools/percentage-calculator',
  'Use Tool',
  0,
  0,
  true,
  'embedded',
  '/tools/percentage-calculator'
),
(
  'be8c9d0e-2345-6789-abcd-ef0123456789',
  'BMI Calculator', 
  'bmi-calculator',
  'Calculate your Body Mass Index using metric or imperial units.',
  '/src/assets/bmi-calculator-icon.jpg',
  'a3f55a64-e095-4cb8-a4d4-1dbc703051d2', -- Productivity Apps category
  'free_tools',
  true,
  false,
  true,
  false,
  false,
  false,
  '/tools/bmi-calculator',
  'Use Tool',
  0,
  0,
  true,
  'embedded',
  '/tools/bmi-calculator'
);