-- Add sample tool insights and discovered tools data for demonstration
INSERT INTO public.tool_insights (insight_type, title, description, category, priority, action_required, related_tool_data) VALUES
  ('missing_popular', 'Missing Popular AI Writing Tools', 'Your directory is missing several trending AI writing tools that competitors are featuring', 'AI Tools', 'high', 'Consider adding: Jasper AI, Copy.ai, Writesonic to compete better', '{"competitor_count": 15, "search_volume": 50000, "tools": ["Jasper AI", "Copy.ai", "Writesonic"]}'),
  ('new_competitor', 'New AI Tool Launched - Claude 3.5 Sonnet', 'Anthropic launched Claude 3.5 Sonnet which is gaining massive traction (100k+ users)', 'AI Tools', 'urgent', 'Add Claude 3.5 Sonnet to your directory immediately - high conversion potential', '{"launch_date": "2024-01-15", "user_growth": "100000+", "affiliate_available": true}'),
  ('affiliate_opportunity', 'High-Paying Affiliate Program Available', 'Notion now offers $200 per conversion affiliate program for productivity tools', 'Productivity', 'medium', 'Update Notion listing with new affiliate link to increase revenue', '{"commission": "$200", "conversion_rate": "8.5%", "estimated_monthly": "$2400"}'),
  ('missing_popular', 'Gap in Design Tools Category', 'Missing 5 popular design tools that get 200k+ monthly searches', 'Design', 'high', 'Add Canva Pro, Adobe Express, Figma, Sketch, InVision to capture design traffic', '{"missing_tools": 5, "monthly_searches": 200000, "revenue_potential": "$5000"}'),
  ('trend_analysis', 'AI Automation Tools Trending Up 300%', 'AI automation category showing explosive growth - your directory has only 2 tools', 'AI Tools', 'urgent', 'Rapidly expand AI automation section - Zapier, Make.com, Bardeen are must-haves', '{"growth_rate": "300%", "current_tools": 2, "recommended_minimum": 10}'),
  ('competitor_analysis', 'ProductHunt Winners Missing', '8 Product Hunt winners from last month are missing from your directory', 'Mixed', 'medium', 'Review and add recent ProductHunt daily/weekly winners to stay current', '{"missing_winners": 8, "timeframe": "last_month", "estimated_traffic": "50000"}');

INSERT INTO public.discovered_tools (name, description, category, source_platform, external_url, tags, has_affiliate_program, affiliate_info, priority_score, pricing_info) VALUES
  ('Claude 3.5 Sonnet', 'Advanced AI assistant by Anthropic with superior reasoning capabilities', 'AI Tools', 'producthunt', 'https://claude.ai', ARRAY['AI', 'Assistant', 'Writing', 'Coding'], true, '{"commission_rate": "30%", "cookie_duration": "30_days", "program_url": "https://anthropic.com/partners"}', 95, '{"pricing": "Free tier + $20/month Pro"}'),
  ('Perplexity AI Pro', 'AI-powered search engine with real-time information and citations', 'AI Tools', 'github', 'https://perplexity.ai', ARRAY['Search', 'AI', 'Research'], true, '{"commission_rate": "25%", "cookie_duration": "60_days"}', 90, '{"pricing": "$20/month Pro plan"}'),
  ('Gamma', 'AI-powered presentation and website builder', 'Design', 'producthunt', 'https://gamma.app', ARRAY['Presentations', 'AI', 'Design'], false, '{}', 85, '{"pricing": "Free + $10/month Plus"}'),
  ('Replit AI', 'AI-powered collaborative coding platform', 'Developer Tools', 'github', 'https://replit.com', ARRAY['Coding', 'AI', 'Collaboration'], true, '{"commission_rate": "20%", "program_url": "https://replit.com/partners"}', 80, '{"pricing": "Free + $7/month Hacker"}'),
  ('Runway ML', 'AI video generation and editing platform', 'AI Tools', 'producthunt', 'https://runwayml.com', ARRAY['Video', 'AI', 'Editing'], true, '{"commission_rate": "15%", "cookie_duration": "45_days"}', 88, '{"pricing": "$12/month Standard"}'),
  ('Framer AI', 'AI website builder with advanced design capabilities', 'Design', 'manual', 'https://framer.com', ARRAY['Website Builder', 'AI', 'Design'], true, '{"commission_rate": "30%", "program_url": "https://framer.com/partners"}', 82, '{"pricing": "$5/month Mini + $20/month Basic"}'),
  ('Linear', 'Modern project management for software teams', 'Productivity', 'github', 'https://linear.app', ARRAY['Project Management', 'Development', 'Teams'], false, '{}', 75, '{"pricing": "Free + $8/month Standard"}'),
  ('Luma AI', 'AI-powered 3D capture and neural rendering', 'AI Tools', 'producthunt', 'https://lumalabs.ai', ARRAY['3D', 'AI', 'Capture'], false, '{}', 78, '{"pricing": "Free + Premium tiers"}');