-- Add sample products across all categories for testing
INSERT INTO products (name, slug, description, rich_description, image_url, category_id, product_type, is_free, is_featured, is_newly_launched, is_popular, is_trending, is_editors_choice, original_price, discounted_price, currency, affiliate_link, cta_button_text, views_count, saves_count, revenue_type) VALUES
-- AI Tools (get a few category IDs first)
('ChatGPT Pro Assistant', 'chatgpt-pro-assistant', 'Advanced AI writing assistant with GPT-4 integration', '<p>Transform your writing with our advanced AI assistant powered by GPT-4. Features include content generation, editing, and optimization tools.</p>', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400', (SELECT id FROM categories WHERE slug LIKE '%ai%' LIMIT 1), 'ai_tools', false, true, true, true, false, false, 29.99, 19.99, 'USD', 'https://example.com/chatgpt-pro', 'Try Free', 1250, 89, 'subscription'),

('AI Image Generator', 'ai-image-generator', 'Create stunning images from text prompts using advanced AI', '<p>Generate professional-quality images from simple text descriptions. Perfect for content creators, marketers, and designers.</p>', 'https://images.unsplash.com/photo-1686191128892-3c15e2fae3d5?w=400', (SELECT id FROM categories WHERE slug LIKE '%ai%' LIMIT 1), 'ai_tools', true, true, false, true, true, true, 0, 0, 'USD', 'https://example.com/ai-image-gen', 'Generate Now', 2340, 156, 'free'),

('Voice AI Cloning Tool', 'voice-ai-cloning', 'Clone any voice with just 3 minutes of audio', '<p>Revolutionary voice cloning technology that creates natural-sounding speech in any voice with minimal training data.</p>', 'https://images.unsplash.com/photo-1589254065878-42c9da997008?w=400', (SELECT id FROM categories WHERE slug LIKE '%ai%' LIMIT 1), 'ai_tools', false, false, true, false, true, false, 49.99, 39.99, 'USD', 'https://example.com/voice-clone', 'Clone Voice', 987, 67, 'one_time'),

-- Software Tools
('Project Management Suite', 'project-management-suite', 'Complete project management solution for teams', '<p>Streamline your team collaboration with task management, time tracking, and reporting tools all in one platform.</p>', 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400', (SELECT id FROM categories WHERE slug LIKE '%productivity%' OR slug LIKE '%business%' LIMIT 1), 'software', false, true, false, true, false, true, 99.99, 79.99, 'USD', 'https://example.com/project-mgmt', 'Start Free Trial', 3456, 234, 'subscription'),

('Free Task Organizer', 'free-task-organizer', 'Simple and effective task management tool', '<p>Organize your daily tasks with our intuitive interface. Features include priority setting, due dates, and progress tracking.</p>', 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400', (SELECT id FROM categories WHERE slug LIKE '%productivity%' OR slug LIKE '%business%' LIMIT 1), 'software', true, false, false, true, false, false, 0, 0, 'USD', 'https://example.com/task-org', 'Download Free', 1876, 134, 'free'),

('Analytics Dashboard Pro', 'analytics-dashboard-pro', 'Advanced analytics and reporting platform', '<p>Get deep insights into your business performance with customizable dashboards, real-time data, and automated reports.</p>', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400', (SELECT id FROM categories WHERE slug LIKE '%analytics%' OR slug LIKE '%business%' LIMIT 1), 'software', false, false, false, false, true, true, 199.99, 149.99, 'USD', 'https://example.com/analytics-pro', 'View Demo', 2145, 178, 'subscription'),

-- Digital Products
('Ultimate Design Templates Pack', 'design-templates-pack', '500+ professional design templates for any project', '<p>Save hours of design work with our comprehensive template collection. Includes social media posts, presentations, logos, and more.</p>', 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=400', (SELECT id FROM categories WHERE slug LIKE '%design%' OR slug LIKE '%creative%' LIMIT 1), 'digital_products', false, true, true, false, false, true, 79.99, 49.99, 'USD', 'https://example.com/templates', 'Download Now', 1567, 98, 'one_time'),

('Stock Photo Bundle', 'stock-photo-bundle', '10,000 high-resolution stock photos', '<p>Professional stock photography collection covering business, nature, technology, and lifestyle themes. Perfect for websites and marketing.</p>', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400', (SELECT id FROM categories WHERE slug LIKE '%design%' OR slug LIKE '%creative%' LIMIT 1), 'digital_products', false, false, false, true, true, false, 149.99, 99.99, 'USD', 'https://example.com/stock-photos', 'Get Bundle', 2234, 145, 'one_time'),

('Free Icon Pack', 'free-icon-pack', '200 premium icons for your projects', '<p>Beautiful, consistent icon set perfect for web and mobile applications. Available in multiple formats including SVG, PNG, and icon fonts.</p>', 'https://images.unsplash.com/photo-1618477247222-acbdb0e159b3?w=400', (SELECT id FROM categories WHERE slug LIKE '%design%' OR slug LIKE '%creative%' LIMIT 1), 'digital_products', true, false, true, false, false, false, 0, 0, 'USD', 'https://example.com/free-icons', 'Download Free', 3456, 267, 'free'),

-- Free Tools
('Password Generator Pro', 'password-generator-pro', 'Generate secure passwords instantly', '<p>Create strong, unique passwords with customizable criteria. Includes password strength checker and secure sharing options.</p>', 'https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400', (SELECT id FROM categories WHERE slug LIKE '%security%' OR slug LIKE '%utility%' LIMIT 1), 'free_tools', true, true, false, true, false, false, 0, 0, 'USD', 'https://example.com/password-gen', 'Generate Password', 4567, 289, 'free'),

('Color Palette Generator', 'color-palette-generator', 'Create beautiful color schemes for your designs', '<p>Generate harmonious color palettes for your design projects. Export in multiple formats and save your favorite combinations.</p>', 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=400', (SELECT id FROM categories WHERE slug LIKE '%design%' OR slug LIKE '%creative%' LIMIT 1), 'free_tools', true, false, true, true, true, false, 0, 0, 'USD', 'https://example.com/color-palette', 'Create Palette', 2890, 201, 'free'),

('QR Code Generator', 'qr-code-generator', 'Generate custom QR codes for any purpose', '<p>Create QR codes for URLs, text, contact info, and more. Customize colors, add logos, and download in various formats.</p>', 'https://images.unsplash.com/photo-1606450153349-4c5aa5637ccf?w=400', (SELECT id FROM categories WHERE slug LIKE '%utility%' OR slug LIKE '%marketing%' LIMIT 1), 'free_tools', true, false, false, true, false, true, 0, 0, 'USD', 'https://example.com/qr-generator', 'Generate QR', 3234, 234, 'free'),

('Text to Speech Tool', 'text-to-speech-tool', 'Convert text to natural-sounding speech', '<p>Transform written content into realistic audio using advanced text-to-speech technology. Multiple voices and languages available.</p>', 'https://images.unsplash.com/photo-1590650516494-0c8e4a4dd67e?w=400', (SELECT id FROM categories WHERE slug LIKE '%ai%' OR slug LIKE '%utility%' LIMIT 1), 'free_tools', true, true, true, false, true, false, 0, 0, 'USD', 'https://example.com/text-to-speech', 'Try Now', 1876, 134, 'free'),

-- Additional Software
('Video Editing Studio', 'video-editing-studio', 'Professional video editing software', '<p>Create stunning videos with our professional-grade editing tools. Includes effects, transitions, and advanced color grading.</p>', 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=400', (SELECT id FROM categories WHERE slug LIKE '%video%' OR slug LIKE '%creative%' LIMIT 1), 'software', false, false, true, true, false, true, 299.99, 199.99, 'USD', 'https://example.com/video-editor', 'Download Trial', 2345, 167, 'one_time'),

('Email Marketing Platform', 'email-marketing-platform', 'Complete email marketing solution', '<p>Design, send, and track email campaigns with ease. Includes automation, segmentation, and detailed analytics.</p>', 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400', (SELECT id FROM categories WHERE slug LIKE '%marketing%' OR slug LIKE '%business%' LIMIT 1), 'software', false, true, false, false, true, false, 89.99, 69.99, 'USD', 'https://example.com/email-marketing', 'Start Campaign', 1789, 123, 'subscription');