// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gazyicdietwqakxnbwmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhenlpY2RpZXR3cWFreG5id21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzcwOTQsImV4cCI6MjA3MzM1MzA5NH0.eBUAyQascpbFEk0KHThSbIYUVsXqpI0zxijcPZ4_0oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});